### ISSUE TITLE
[Question] Number of stickers per team

### ISSUE THREAD

**Issue by IvanFrescas** [Josefrancasrod/world-cup-collectibles#13]
There is a recent announcement where the number of players per selection increased to 26, is a change needed in the app for more stickers?

**Comment by Josefrancasrod** [comment]
Maybe, right now the app is based on the 2018's version of the book, I'm waiting for the official release of the 2022 album. But, the past edition don't have the previous 23 players, only have 18 players, the federation logo and a team photo.
